export enum PeriodType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  TWO_WEEKS = 'TWO_WEEKS',
  THREE_WEEKS = 'THREE_WEEKS',
  MONTHLY = 'MONTHLY',
  TWO_MONTHS = 'TWO_MONTHS',
  QUARTERLY = 'QUARTERLY',
  SEMI_ANNUAL = 'SEMI_ANNUAL',
  YEARLY = 'YEARLY',
}
